# docker-compose.yml

services:
  node1:
    build: .
    command: uvicorn node:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - blockchain-net

  node2:
    build: .
    command: >
      sh -c "sleep 5 && 
      uvicorn node:app --host 0.0.0.0 --port 8001 &&
      curl -X POST http://node1:8000/nodes -H 'Content-Type: application/json' -d '{\"nodes\": [\"http://node2:8001\"]}'"
    ports:
      - "8001:8001"
    networks:
      - blockchain-net
    depends_on:
      - node1

  node3:
    build: .
    command: >
      sh -c "sleep 10 && 
      uvicorn node:app --host 0.0.0.0 --port 8002 &&
      curl -X POST http://node1:8000/nodes -H 'Content-Type: application/json' -d '{\"nodes\": [\"http://node3:8002\"]}' &&
      curl -X POST http://node2:8001/nodes -H 'Content-Type: application/json' -d '{\"nodes\": [\"http://node3:8002\"]}'"
    ports:
      - "8002:8002"
    networks:
      - blockchain-net
    depends_on:
      - node1
      - node2

  client:
    build: .
    command: uvicorn blockchain_client:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"
    networks:
      - blockchain-net
    depends_on:
      - node1
      - node2
      - node3

networks:
  blockchain-net:
    driver: bridge